---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/boards/{id}/filter_stories":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: filter_stories board
      responses:
        '200':
          description: successful
  "/boards":
    get:
      summary: list boards
      responses:
        '200':
          description: successful
    post:
      summary: create board
      responses:
        '200':
          description: successful
  "/boards/new":
    get:
      summary: new board
      responses:
        '200':
          description: successful
  "/boards/{id}/edit":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit board
      responses:
        '200':
          description: successful
  "/boards/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show board
      responses:
        '200':
          description: successful
    patch:
      summary: update board
      responses:
        '200':
          description: successful
    put:
      summary: update board
      responses:
        '200':
          description: successful
    delete:
      summary: delete board
      responses:
        '200':
          description: successful
  "/":
    get:
      summary: list boards
      responses:
        '200':
          description: successful
  "/boards/{board_id}/columns":
    parameters:
    - name: board_id
      in: path
      description: board_id
      required: true
      schema:
        type: string
    get:
      summary: list columns
      responses:
        '200':
          description: successful
    post:
      summary: create column
      responses:
        '200':
          description: successful
  "/boards/{board_id}/columns/new":
    parameters:
    - name: board_id
      in: path
      description: board_id
      required: true
      schema:
        type: string
    get:
      summary: new column
      responses:
        '200':
          description: successful
  "/boards/{board_id}/columns/{id}/edit":
    parameters:
    - name: board_id
      in: path
      description: board_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit column
      responses:
        '200':
          description: successful
  "/boards/{board_id}/columns/{id}":
    parameters:
    - name: board_id
      in: path
      description: board_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show column
      responses:
        '200':
          description: successful
    patch:
      summary: update column
      responses:
        '200':
          description: successful
    put:
      summary: update column
      responses:
        '200':
          description: successful
    delete:
      summary: delete column
      responses:
        '200':
          description: successful
  "/boards/{board_id}/columns/{column_id}/stories/filter":
    parameters:
    - name: board_id
      in: path
      description: board_id
      required: true
      schema:
        type: string
    - name: column_id
      in: path
      description: column_id
      required: true
      schema:
        type: string
    get:
      summary: filter story
      responses:
        '200':
          description: successful
  "/boards/{board_id}/columns/{column_id}/stories":
    parameters:
    - name: board_id
      in: path
      description: board_id
      required: true
      schema:
        type: string
    - name: column_id
      in: path
      description: column_id
      required: true
      schema:
        type: string
    get:
      summary: list stories
      responses:
        '200':
          description: successful
    post:
      summary: create story
      responses:
        '200':
          description: successful
  "/boards/{board_id}/columns/{column_id}/stories/new":
    parameters:
    - name: board_id
      in: path
      description: board_id
      required: true
      schema:
        type: string
    - name: column_id
      in: path
      description: column_id
      required: true
      schema:
        type: string
    get:
      summary: new story
      responses:
        '200':
          description: successful
  "/boards/{board_id}/columns/{column_id}/stories/{id}/edit":
    parameters:
    - name: board_id
      in: path
      description: board_id
      required: true
      schema:
        type: string
    - name: column_id
      in: path
      description: column_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit story
      responses:
        '200':
          description: successful
  "/boards/{board_id}/columns/{column_id}/stories/{id}":
    parameters:
    - name: board_id
      in: path
      description: board_id
      required: true
      schema:
        type: string
    - name: column_id
      in: path
      description: column_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show story
      responses:
        '200':
          description: successful
    patch:
      summary: update story
      responses:
        '200':
          description: successful
    put:
      summary: update story
      responses:
        '200':
          description: successful
    delete:
      summary: delete story
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
