---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  schemas:
    Board:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        created_at:
          type: string
          format: datetime
        updated_at:
          type: string
          format: datetime
        deleted_at:
          type: string
          format: datetime
          nullable: true
      required:
      - id
      - title
      - created_at
      - updated_at
    Column:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        board_id:
          type: integer
        order:
          type: integer
          default: 0
        created_at:
          type: string
          format: datetime
        updated_at:
          type: string
          format: datetime
        deleted_at:
          type: string
          format: datetime
          nullable: true
      required:
      - id
      - title
      - board_id
      - order
      - created_at
      - updated_at
    Story:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        column_id:
          type: integer
        order:
          type: integer
          default: 0
        description:
          type: string
          nullable: true
        status:
          type: string
          nullable: true
        due_date:
          type: string
          format: date_time
          nullable: true
        created_at:
          type: string
          format: datetime
        updated_at:
          type: string
          format: datetime
        deleted_at:
          type: string
          format: datetime
          nullable: true
      required:
      - id
      - title
      - column_id
      - order
      - created_at
      - updated_at
paths:
  "/boards":
    get:
      summary: Retrieves all boards
      tags:
      - Boards
      operationId: listBoards
      description: Fetches all boards with optional filtering
      parameters:
      - name: showall
        in: query
        description: Show all Boards > Columns > Stories
        schema:
          type: string
      responses:
        '200':
          description: Boards retrieved successfully
    post:
      summary: Create a new board
      tags:
      - Boards
      operationId: createBoard
      description: Creates a new board and returns it
      parameters: []
      responses:
        '201':
          description: Board created successfully
  "/boards/{id}":
    get:
      summary: Retrieves a board
      tags:
      - Boards
      operationId: getBoard
      description: Fetches a board by id
      parameters:
      - name: id
        in: path
        required: true
        description: Board id
        schema:
          type: integer
      responses:
        '200':
          description: Board retrieved successfully
    put:
      summary: Update a board
      tags:
      - Boards
      operationId: updateBoard
      description: Updates a board by id
      parameters:
      - name: id
        in: path
        required: true
        description: Board id
        schema:
          type: integer
      responses:
        '200':
          description: Board updated successfully
    delete:
      summary: Delete a board
      tags:
      - Boards
      operationId: deleteBoard
      description: Deletes a board by id
      parameters:
      - name: id
        in: path
        required: true
        description: Board id
        schema:
          type: integer
      responses:
        '204':
          description: Board deleted successfully
  "/boards/{board_id}/columns":
    get:
      summary: Retrieves all columns on a board
      tags:
      - Columns
      operationId: listColumns
      description: Fetches all columns linked to a board
      parameters:
      - name: board_id
        in: path
        required: true
        description: Board id
        schema:
          type: integer
      responses:
        '200':
          description: Columns retrieved successfully
    post:
      summary: Create a new column
      tags:
      - Columns
      operationId: createColumn
      description: Creates a new column and returns it
      parameters:
      - name: board_id
        in: path
        required: true
        description: Board id
        schema:
          type: integer
      responses:
        '201':
          description: Column created successfully
  "/boards/{board_id}/columns/{id}":
    get:
      summary: Retrieves a column
      tags:
      - Columns
      operationId: getColumn
      description: Fetches a column by id
      parameters:
      - name: board_id
        in: path
        required: true
        description: Board id
        schema:
          type: integer
      - name: id
        in: path
        required: true
        description: Column id
        schema:
          type: integer
      responses:
        '200':
          description: Column retrieved successfully
    put:
      summary: Update a column
      tags:
      - Columns
      operationId: updateColumn
      description: Updates a column by id
      parameters:
      - name: board_id
        in: path
        required: true
        description: Board id
        schema:
          type: integer
      - name: id
        in: path
        required: true
        description: Column id
        schema:
          type: integer
      responses:
        '200':
          description: Column updated successfully
    delete:
      summary: Delete a column
      tags:
      - Columns
      operationId: deleteColumn
      description: Deletes a column by id
      parameters:
      - name: board_id
        in: path
        required: true
        description: Board id
        schema:
          type: integer
      - name: id
        in: path
        required: true
        description: Column id
        schema:
          type: integer
      responses:
        '204':
          description: Column deleted successfully
  "/boards/{board_id}/columns/{column_id}/stories":
    get:
      summary: Retrieves all stories on a column
      tags:
      - Stories
      operationId: listStories
      description: Fetches all stories linked to a column
      parameters:
      - name: board_id
        in: path
        required: true
        description: Board id
        schema:
          type: integer
      - name: column_id
        in: path
        required: true
        description: Column id
        schema:
          type: integer
      responses:
        '200':
          description: Stories retrieved successfully
    post:
      summary: Create a new story
      tags:
      - Stories
      operationId: createStory
      description: Creates a new story and returns it
      parameters:
      - name: board_id
        in: path
        required: true
        description: Board id
        schema:
          type: integer
      - name: column_id
        in: path
        required: true
        description: Column id
        schema:
          type: integer
      responses:
        '201':
          description: Story created successfully
  "/boards/{board_id}/columns/{column_id}/stories/{id}":
    get:
      summary: Retrieves a story
      tags:
      - Stories
      operationId: getStory
      description: Fetches a story by id
      parameters:
      - name: board_id
        in: path
        required: true
        description: Board id
        schema:
          type: integer
      - name: column_id
        in: path
        required: true
        description: Column id
        schema:
          type: integer
      - name: id
        in: path
        required: true
        description: Story id
        schema:
          type: integer
      responses:
        '200':
          description: Story retrieved successfully
    put:
      summary: Update a story
      tags:
      - Stories
      operationId: updateStory
      description: Updates a story by id
      parameters:
      - name: board_id
        in: path
        required: true
        description: Board id
        schema:
          type: integer
      - name: column_id
        in: path
        required: true
        description: Column id
        schema:
          type: integer
      - name: id
        in: path
        required: true
        description: Story id
        schema:
          type: integer
      responses:
        '200':
          description: Story updated successfully
    delete:
      summary: Delete a story
      tags:
      - Stories
      operationId: deleteStory
      description: Deletes a story by id
      parameters:
      - name: board_id
        in: path
        required: true
        description: Board id
        schema:
          type: integer
      - name: column_id
        in: path
        required: true
        description: Column id
        schema:
          type: integer
      - name: id
        in: path
        required: true
        description: Story id
        schema:
          type: integer
      responses:
        '204':
          description: Story deleted successfully
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
